package errors

const STATUS_UNKNOWN = "UNKNOWN"
const STATUS_NOT_FOUND = "NOT_FOUND"
const STATUS_KUBERNETES_CONFIG = "KUBERNETES_CONFIG"
const STATUS_BAD_REQUEST = "BAD_REQUEST"
const STATUS_UNAUTHORIZED = "UNAUTHORIZED"
const STATUS_UNAUTHORIZED_EXPIRED = "UNAUTHORIZED_EXPIRED"
const STATUS_FORBIDDEN = "STATUS_FORBIDDEN"
