name: Electron Nightly Build
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #   ref: "develop"
        
    - name: Build web
      run: |
        yarn install
        yarn run build:web
        yarn run build:electron

    - name: Build executable
      run: | 
        yarn run release:electron

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist
